<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class LocationTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $locations =  [
            [
                'name' => 'Eastern Cape',
                'children' => [
                        ['name' => 'Adelaide'],
                        ['name' => 'Alice'],
                        ['name' => 'Aliwal North'],
                        ['name' => 'Barkly East'],
                        ['name' => 'Bhisho'],
                        ['name' => 'Bizana'],
                        ['name' => 'Burgersdorp'],
                        ['name' => 'Butterworth'],
                        ['name' => 'Coffee Bay'],
                        ['name' => 'Cradock'],
                        ['name' => 'Despatch'],
                        ['name' => 'East London'],
                        ['name' => 'Elliot'],
                        ['name' => 'Flagstaff'],
                        ['name' => 'Fort Beaufort'],
                        ['name' => 'Graaff-Reinet'],
                        ['name' => 'Grahamstown'],
                        ['name' => 'Hogsback'],
                        ['name' => 'Jansenville'],
                        ['name' => 'Jeffreys Bay'],
                        ['name' => 'Kareedouw'],
                        ['name' => 'King Williams Town'],
                        ['name' => 'Kirkwood'],
                        ['name' => 'Matatiele'],
                        ['name' => 'Mdantsane'],
                        ['name' => 'Middleburg'],
                        ['name' => 'Port Alfred'],
                        ['name' => 'Port Elizabeth'],
                        ['name' => 'Port St Johns'],
                        ['name' => 'Queenstown'],
                        ['name' => 'Somerset East'],
                        ['name' => 'St Francis Bay'],
                        ['name' => 'Stutterheim'],
                        ['name' => 'Uitenhage'],
                        ['name' => 'Umtata'],
                        ['name' => 'Willowmore'],
                        ['name' => 'Willowvale'],
                        ['name' => 'Other Eastern Cape'],
                ],
            ],

            [
                'name' => 'Free State',
                'children' => [
                        ['name' => 'Bethlehem'],
                        ['name' => 'Bloemfontein'],
                        ['name' => 'Botshabelo'],
                        ['name' => 'Brandfort'],
                        ['name' => 'Bultfontein'],
                        ['name' => 'Clocolan'],
                        ['name' => 'Deneysville'],
                        ['name' => 'Ficksburg'],
                        ['name' => 'Frankfort'],
                        ['name' => 'Harrismith'],
                        ['name' => 'Heilbron'],
                        ['name' => 'Hennenburg'],
                        ['name' => 'Hoopstad'],
                        ['name' => 'Koffiefontein'],
                        ['name' => 'Koppies'],
                        ['name' => 'Kroonstad'],
                        ['name' => 'Ladybrand'],
                        ['name' => 'Memel'],
                        ['name' => 'Other Free State'],
                        ['name' => 'Parys'],
                        ['name' => 'Reitz'],
                        ['name' => 'Sasolburg'],
                        ['name' => 'Senekal'],
                        ['name' => 'Springfontein'],
                        ['name' => 'Thaba Nchu'],
                        ['name' => 'Theunissen'],
                        ['name' => 'Vijoenskroon'],
                        ['name' => 'Virginia'],
                        ['name' => 'Vrede'],
                        ['name' => 'Vredefort'],
                        ['name' => 'Welkom'],
                        ['name' => 'Wesselsbron'],
                        ['name' => 'Winburg'],
                ],
            ],

            [
                'name' => 'Gauteng',
                'children' => [
                    [
                        'name' => 'East Rand',
                        'children' => [
                            ['name' => 'Alberton'],
                            ['name' => 'Bedfordview'],
                            ['name' => 'Benoni'],
                            ['name' => 'Boksburg'],
                            ['name' => 'Brakpan'],
                            ['name' => 'Edenvale'],
                            ['name' => 'Germiston'],
                            ['name' => 'Kempton Park'],
                            ['name' => 'Other'],
                            ['name' => 'Springs'],
                            ['name' => 'Tembisa'],
                        ],
                        
                    ],
                    [
                        'name' => 'Johannesburg',
                        'children' => [
                            ['name' => 'Alexandra'],
                            ['name' => 'Bram Fischerville'],
                            ['name' => 'Bryanston'],
                            ['name' => 'Constantia Kloof'],
                            ['name' => 'Cosmo City'],
                            ['name' => 'Diepkloof'],
                            ['name' => 'Diepsloot'],
                            ['name' => 'Dobsonville'],
                            ['name' => 'Douglasdale'],
                            ['name' => 'Emmarentia'],
                            ['name' => 'Ennerdale'],
                            ['name' => 'Fairland'],
                            ['name' => 'Fourways'],
                            ['name' => 'Greenside'],
                            ['name' => 'Highlands North'],
                            ['name' => 'Illovo'],
                            ['name' => 'Inner City'],
                            ['name' => 'Ivory Park'],
                            ['name' => 'Johannesburg CBD'],
                            ['name' => 'Johannesburg South'],
                            ['name' => 'Katlehong'],
                            ['name' => 'Kensington'],
                            ['name' => 'Lanseria'],
                            ['name' => 'Lenasia'],
                            ['name' => 'Meadowlands'],
                            ['name' => 'Mellvile'],
                            ['name' => 'Midrand'],
                            ['name' => 'North Riding'],
                            ['name' => 'Northcliff'],
                            ['name' => 'Northgate'],
                            ['name' => 'Other'],
                            ['name' => 'Parkhust'],
                            ['name' => 'Parktown'],
                            ['name' => 'Protea Glen'],
                            ['name' => 'Randburg'],
                            ['name' => 'Randpark Ridge'],
                            ['name' => 'Roodeport'],
                            ['name' => 'Rosebank'],
                            ['name' => 'Sandton'],
                            ['name' => 'Soughgate'],
                            ['name' => 'Soweto'],
                            ['name' => 'Sunninghill'],
                            ['name' => 'Walkerville'],
                            ['name' => 'Woodmead'],
                        ],
                    ],
                    [
                        'name' => 'Pretoria',
                        'children' => [
                            ['name' => 'Arcadia'],
                            ['name' => 'Bronkhorstspruit'],
                            ['name' => 'Brooklyn'],
                            ['name' => 'Centurion'],
                            ['name' => 'City Centre'],
                            ['name' => 'Eastern Pretoria'],
                            ['name' => 'Ga Rankuwa'],
                            ['name' => 'Hatfield'],
                            ['name' => 'Mamelodi'],
                            ['name' => 'Menlyn Park'],
                            ['name' => 'Northern Pretoria'],
                            ['name' => 'Other'],
                            ['name' => 'Pretoria West'],
                            ['name' => 'Sunnyside & Arcadia'],
                        ],
                        
                    ],
                    [
                        'name' => 'Sedibeng',
                        'children' => [
                            ['name' => 'Evaton'],
                            ['name' => 'Heidelberg'],
                            ['name' => 'Orange Farm'],
                            ['name' => 'Meyerton'],
                            ['name' => 'Other'],
                            ['name' => 'Vreeniging'],
                            ['name' => 'Vanderbijlpark'],
                        ],
                        
                    ],
                    [
                        'name' => 'West Rand',
                        'children' => [
                            ['name' => 'Carletonville'],
                            ['name' => 'Kagiso'],
                            ['name' => 'Krugersdorp'],
                            ['name' => 'Other'],
                            ['name' => 'Randfontein'],
                            ['name' => 'Westonaria'],
                        ],
                        
                    ],
                ],
            ],


            [
                'name' => 'KwaZulu-Natal',
                    'children' => [
                        [    
                            'name' => 'Drakensberg',
                            'children' => [
                                    ['name' => 'Newcastle'],
                                    ['name' => 'Other'],
                                    ['name' => 'Ulundi'],
                                    ['name' => 'Umzinyathi'],
                                    ['name' => 'Ladysmith'],
                                    ['name' => 'Vryheid'],
                                    ['name' => 'Zululand'],
                            ],
                        ],
                        [    
                            'name' => 'Durban City',
                            'children' => [
                                    ['name' => 'Bearea & Musgrave'],
                                    ['name' => 'Chatsworthy'],
                                    ['name' => 'City Centre'],
                                    ['name' => 'Clare Hills'],
                                    ['name' => 'Golden Mile'],
                                    ['name' => 'Greyville'],
                                    ['name' => 'Inanda'],
                                    ['name' => 'KwaMhashu'],
                                    ['name' => 'Morningside'],
                                    ['name' => 'Other'],
                                    ['name' => 'Point & Harbour'],
                                    ['name' => 'Umbilo'],
                                    ['name' => 'Umlazi'],
                            ],
                        ],

                        [    
                            'name' => 'Midlands',
                            'children' => [
                                    ['name' => 'Estcourt'],
                                    ['name' => 'Greytown'],
                                    ['name' => 'Howick'],
                                    ['name' => 'Kokstad'],
                                    ['name' => 'Other'],
                                    ['name' => 'Pietermaritzburg'],
                                    ['name' => 'Richmond'],
                            ],
                        ],

                        [    
                            'name' => 'North Coast',
                            'children' => [
                                    ['name' => 'Ballitoville'],
                                    ['name' => 'Empangeni'],
                                    ['name' => 'Eshowe'],
                                    ['name' => 'Dolphin Coast'],
                                    ['name' => 'Other'],
                                    ['name' => 'Richards Bay'],
                                    ['name' => 'Stanger'],
                                    ['name' => 'Umkhanyakude'],
                            ],
                        ],

                        [    
                            'name' => 'North Suburbs',
                            'children' => [
                                    ['name' => 'Durban North'],
                                    ['name' => 'Mount Edgecombe'],
                                    ['name' => 'Newlands'],
                                    ['name' => 'Other'],
                                    ['name' => 'Phoenix'],
                                    ['name' => 'Tongaat'],
                                    ['name' => 'Umdloti Beach'],
                                    ['name' => 'Umhlanga'],
                                    ['name' => 'Verulum'],
                            ],
                        ],

                        [    
                            'name' => 'South Coast',
                            'children' => [
                                    ['name' => 'Hibiscus Coast'],
                                    ['name' => 'Margate'],
                                    ['name' => 'Port Edward'],
                                    ['name' => 'Other'],
                                    ['name' => 'Port Shepstone'],
                                    ['name' => 'Scottburgh'],
                                    ['name' => 'Umdoni'],
                                    ['name' => 'Umzumbe'],
                            ],
                        ],

                        [    
                            'name' => 'South Suburbs',
                            'children' => [
                                    ['name' => 'Amanzintoni'],
                                    ['name' => 'Bluff'],
                                    ['name' => 'Glenmore'],
                                    ['name' => 'Glenwood'],
                                    ['name' => 'Ispingo Beach'],
                                    ['name' => 'Scottburgh'],
                                    ['name' => 'Kingsborough'],
                                    ['name' => 'Other'],
                                    ['name' => 'South Beach'],
                                    ['name' => 'Umkomaas'],
                            ],
                        ],
                        [    
                            'name' => 'West Suburbs',
                            'children' => [
                                    ['name' => 'Drummond'],
                                    ['name' => 'Gillits'],
                                    ['name' => 'Hillcrest'],
                                    ['name' => 'Kloof'],
                                    ['name' => 'New Germany'],
                                    ['name' => 'Pinetown'],
                                    ['name' => 'Pittsburgh'],
                                    ['name' => 'Other'],
                                    ['name' => 'Reservoir Hills'],
                                    ['name' => 'Waterfall'],
                                    ['name' => 'Westville'],
                            ],
                        ],
                    ],
                ],


                [
                    'name' => 'Limpopo',
                    'children' => [
                            ['name' => 'Bela-Bela'],
                            ['name' => 'Dendron'],
                            ['name' => 'Giyani'],
                            ['name' => 'Hoedspruit'],
                            ['name' => 'Lebowakgomo'],
                            ['name' => 'Lephalale'],
                            ['name' => 'Louis Tritchard'],
                            ['name' => 'Lulekani'],
                            ['name' => 'Mankweng'],
                            ['name' => 'Marblehall'],
                            ['name' => 'Modimolle'],
                            ['name' => 'Modjadji'],
                            ['name' => 'Mokopane'],
                            ['name' => 'Musina'],
                            ['name' => 'Mutale'],
                            ['name' => 'Nkowankowa'],
                            ['name' => 'Other'],
                            ['name' => 'Phalaborwa'],
                            ['name' => 'Polokwane'],
                            ['name' => 'Soekmekaar'],
                            ['name' => 'Thabazimbi'],
                            ['name' => 'Thohoyandou'],
                            ['name' => 'Thulamela'],
                            ['name' => 'Tzaneen'],
                    ],
                ],

                
                [
                    'name' => 'Mpumalanga',
                    'children' => [
                            ['name' => 'Balfour'],
                            ['name' => 'Barberton'],
                            ['name' => 'Bethal'],
                            ['name' => 'Breyten'],
                            ['name' => 'Bushbuckridge'],
                            ['name' => 'Carolina'],
                            ['name' => 'Delmas'],
                            ['name' => 'Dullstroom'],
                            ['name' => 'Ekangala'],
                            ['name' => 'Embalenhle'],
                            ['name' => 'Empuluzi'],
                            ['name' => 'Ermelo'],
                            ['name' => 'Greylingstad'],
                            ['name' => 'Groblersdal'],
                            ['name' => 'Hazyview'],
                            ['name' => 'Hendrina'],
                            ['name' => 'Other'],
                            ['name' => 'Komatipoort'],
                            ['name' => 'Kriel'],
                            ['name' => 'KwaNgema'],
                            ['name' => 'Lebogang'],
                            ['name' => 'Lybenburg'],
                            ['name' => 'Machadodorp'],
                            ['name' => 'Malelane'],
                            ['name' => 'Middlesburg'],
                            ['name' => 'New-Location'],
                            ['name' => 'Orgies'],
                            ['name' => 'Piet Retief'],
                            ['name' => 'Sabie'],
                            ['name' => 'Secunda'],
                            ['name' => 'Siyabuswa'],
                            ['name' => 'Standerton'],
                            ['name' => 'Tritchard'],
                            ['name' => 'Volksrust'],
                            ['name' => 'Wakkerstroom'],
                            ['name' => 'Witbank'],
                            ['name' => 'Witrivier'],
                            ['name' => 'eMakhazeni'],
                    ],
                ],

                     
                [
                    'name' => 'North West',
                    'children' => [
                            ['name' => 'Bloemhof'],
                            ['name' => 'Bray'],
                            ['name' => 'Brits'],
                            ['name' => 'Christiana'],
                            ['name' => 'Delareyville'],
                            ['name' => 'Fochville'],
                            ['name' => 'Hartbeespoort'],
                            ['name' => 'Klerksdorp'],
                            ['name' => 'Koster'],
                            ['name' => 'Litchenburg'],
                            ['name' => 'Mabopane'],
                            ['name' => 'Magaliesberg'],
                            ['name' => 'Mahikeng'],
                            ['name' => 'Mmbatho'],
                            ['name' => 'Mogwase'],
                            ['name' => 'Mothibistad'],
                            ['name' => 'Other'],
                            ['name' => 'Orkney'],
                            ['name' => 'Ottosdal'],
                            ['name' => 'Pomfret'],
                            ['name' => 'Potchefstroom'],
                            ['name' => 'Reivilo'],
                            ['name' => 'Rusternburg'],
                            ['name' => 'Schweizer-Reneke'],
                            ['name' => 'Stella'],
                            ['name' => 'Stilfontein'],
                            ['name' => 'Ventersburg'],
                            ['name' => 'Vryburg'],
                            ['name' => 'Wolmaranstad'],
                            ['name' => 'Zeerust'],
                    ],
                ],

                          
                [
                    'name' => 'Northern Cape',
                    'children' => [
                            ['name' => 'Aggeneys'],
                            ['name' => 'Alexander Bay'],
                            ['name' => 'Barkly West'],
                            ['name' => 'Beeshoek'],
                            ['name' => 'Calvinia'],
                            ['name' => 'Carnavon'],
                            ['name' => 'Colsberg'],
                            ['name' => 'Danielskuil'],
                            ['name' => 'De Aar'],
                            ['name' => 'Douglas'],
                            ['name' => 'Fraseburg'],
                            ['name' => 'Garies'],
                            ['name' => 'Griekwastad'],
                            ['name' => 'Groblershoop'],
                            ['name' => 'Jan Kempdorp'],
                            ['name' => 'Hartswater'],
                            ['name' => 'Other'],
                            ['name' => 'Kathu'],
                            ['name' => 'Keimos'],
                            ['name' => 'Kimberley'],
                            ['name' => 'Kuruman'],
                            ['name' => 'Mier'],
                            ['name' => 'Pampierstad'],
                            ['name' => 'Pofadder'],
                            ['name' => 'Port Nolloth'],
                            ['name' => 'Postmasburg'],
                            ['name' => 'Prieska'],
                            ['name' => 'Ritchie'],
                            ['name' => 'Springbok'],
                            ['name' => 'Strydenburg'],
                            ['name' => 'Sutherland'],
                            ['name' => 'Upington'],
                            ['name' => 'Vanderkloof'],
                            ['name' => 'Victoria West'],
                            ['name' => 'Warrenton'],
                    ],
                ],

                [
                    'name' => 'Western Cape',
                        'children' => [
                            [    
                                'name' => 'Atlantic Seaboards',
                                'children' => [
                                        ['name' => 'Bantry Bay'],
                                        ['name' => 'Hout Bay'],
                                        ['name' => 'Camps Bay'],
                                        ['name' => 'Clifton'],
                                        ['name' => 'Waterfront'],
                                        ['name' => 'Mouille Point'],
                                        ['name' => 'Other'],
                                        ['name' => 'Seapoint'],
                                        ['name' => 'Llandudno'],
                                ],
                            ],
                            [    
                                'name' => 'Cape Flats',
                                'children' => [
                                        ['name' => 'Athlone'],
                                        ['name' => 'Belhar'],
                                        ['name' => 'Blue Downs'],
                                        ['name' => 'Delft'],
                                        ['name' => 'Eerste Rivier'],
                                        ['name' => 'Elsies River'],
                                        ['name' => 'Gugulethu'],
                                        ['name' => 'Khayelitsha'],
                                        ['name' => 'Langa'],
                                        ['name' => 'Other'],
                                        ['name' => 'Mitchells Plain'],
                                ],
                            ],
    
                            [    
                                'name' => 'Cape Town',
                                'children' => [
                                        ['name' => 'Bo-Kaap'],
                                        ['name' => 'Brooklyn'],
                                        ['name' => 'Century City'],
                                        ['name' => 'City Centre'],
                                        ['name' => 'De Waterkant'],
                                        ['name' => 'Devils Peak'],
                                        ['name' => 'Foreshore'],
                                        ['name' => 'Gardens'],
                                        ['name' => 'Higgovale'],
                                        ['name' => 'Maitland'],
                                        ['name' => 'Oranjezicht'],
                                        ['name' => 'Salt River'],
                                        ['name' => 'Tamboerskloof'],
                                        ['name' => 'University Estate'],
                                        ['name' => 'Vredehoek'],
                                        ['name' => 'Woodstock'],
                                        ['name' => 'Other'],
                                ],
                            ],
    
                            [    
                                'name' => 'Cape Winelands',
                                'children' => [
                                        ['name' => 'Ashton'],
                                        ['name' => 'Ceres'],
                                        ['name' => 'Franschhoek'],
                                        ['name' => 'Paarl'],
                                        ['name' => 'Other'],
                                        ['name' => 'Robertson'],
                                        ['name' => 'Stellenbosch'],
                                        ['name' => 'Wellington'],
                                        ['name' => 'Worcester'],
                                ],
                            ],
    
                            [    
                                'name' => 'Central Karoo',
                                'children' => [
                                        ['name' => 'Beaufort West'],
                                        ['name' => 'Klein Karoo'],
                                        ['name' => 'Laingsburg'],
                                        ['name' => 'Other'],
                                        ['name' => 'Prince Albert'],
                                ],
                            ],
    
                            [    
                                'name' => 'Eden',
                                'children' => [
                                        ['name' => 'George'],
                                        ['name' => 'Knysna'],
                                        ['name' => 'Ladysmith'],
                                        ['name' => 'Other'],
                                        ['name' => 'Mosselbaai'],
                                        ['name' => 'Oudtshoorn'],
                                        ['name' => 'Plettenberg Bay'],
                                        ['name' => 'Riversdale'],
                                        ['name' => 'Stanford'],
                                ],
                            ],
    
                            [    
                                'name' => 'Helderberg',
                                'children' => [
                                        ['name' => 'Gordons Bay'],
                                        ['name' => 'Macassar'],
                                        ['name' => 'Other'],
                                        ['name' => 'Somerset West'],
                                        ['name' => 'Strand'],
                                ],
                            ],
                            [    
                                'name' => 'Nothern Suburbs',
                                'children' => [
                                        ['name' => 'Bellville'],
                                        ['name' => 'Brackenfell'],
                                        ['name' => 'Buh Rein'],
                                        ['name' => 'Durbanville'],
                                        ['name' => 'Edgemead'],
                                        ['name' => 'Goodwood'],
                                        ['name' => 'Kensington'],
                                        ['name' => 'Kraaifontein'],
                                        ['name' => 'Kuils River'],
                                        ['name' => 'Milnerton'],
                                        ['name' => 'Montague Gardens'],
                                        ['name' => 'Other'],
                                        ['name' => 'Parow'],
                                        ['name' => 'Plattekloof'],
                                ],
                            ],
                            [    
                                'name' => 'Overberg',
                                'children' => [
                                        ['name' => 'Bettys Bay'],
                                        ['name' => 'Bredasdorp'],
                                        ['name' => 'Caledon'],
                                        ['name' => 'Cape Agulhas'],
                                        ['name' => 'Gansbaai'],
                                        ['name' => 'Hermanus'],
                                        ['name' => 'Kleinmond'],
                                        ['name' => 'Other'],
                                        ['name' => 'Pringle Bay'],
                                        ['name' => 'Swellendam'],
                                        ['name' => 'Villiersdorp'],
                                        ['name' => 'Rooi-Els'],
                                ],
                            ],
                            [    
                                'name' => 'Southern Peninsula',
                                'children' => [
                                        ['name' => 'Capri'],
                                        ['name' => 'Fishhoek'],
                                        ['name' => 'Glencairn'],
                                        ['name' => 'Kalk Bay'],
                                        ['name' => 'Kommetjie'],
                                        ['name' => 'Lakeside'],
                                        ['name' => 'Muizenburg'],
                                        ['name' => 'Noordhoek'],
                                        ['name' => 'Ocean View'],
                                        ['name' => 'Other'],
                                        ['name' => 'Scarborough'],
                                        ['name' => 'Simons Town'],
                                        ['name' => 'Strandfontein'],
                                ],
                            ],
                            [    
                                'name' => 'Southern Suburbs',
                                'children' => [
                                        ['name' => 'Bergviliet'],
                                        ['name' => 'Claremont'],
                                        ['name' => 'Constantia'],
                                        ['name' => 'Crawford'],
                                        ['name' => 'Diep River'],
                                        ['name' => 'Grassy Park'],
                                        ['name' => 'Heathfield'],
                                        ['name' => 'Other'],
                                        ['name' => 'Kenilworth'],
                                        ['name' => 'Kenwyn'],
                                        ['name' => 'Kirstenhof'],
                                        ['name' => 'Lansdowne'],
                                        ['name' => 'Meadowridge'],
                                        ['name' => 'Mowbray'],
                                        ['name' => 'Newlands'],
                                        ['name' => 'Observatory'],
                                        ['name' => 'Ottery'],
                                        ['name' => 'Pinelands'],
                                        ['name' => 'Plumstead'],
                                        ['name' => 'Retreat'],
                                        ['name' => 'Rondebosch'],
                                        ['name' => 'Thornton'],
                                        ['name' => 'Tokai'],
                                        ['name' => 'Wynberg'],
                                ],
                            ],
                            [    
                                'name' => 'West Coast',
                                'children' => [
                                        ['name' => 'Atlantis'],
                                        ['name' => 'Blouberg'],
                                        ['name' => 'Cederberg'],
                                        ['name' => 'Citrusdal'],
                                        ['name' => 'Clan William'],
                                        ['name' => 'Darling'],
                                        ['name' => 'Flamingo Vlei'],
                                        ['name' => 'Other'],
                                        ['name' => 'Hopefield'],
                                        ['name' => 'Lamberts Bay'],
                                        ['name' => 'Langebaan'],
                                        ['name' => 'Malmesbury'],
                                        ['name' => 'Melkbosstrand'],
                                        ['name' => 'Mooreesburg'],
                                        ['name' => 'Parklands'],
                                        ['name' => 'Piketberg'],
                                        ['name' => 'Porteville'],
                                        ['name' => 'Redelinghuys'],
                                        ['name' => 'Riebeeck Kasteel'],
                                        ['name' => 'Saldanha'],
                                        ['name' => 'St Helena Bay'],
                                        ['name' => 'Sunningdale'],
                                        ['name' => 'Tableview'],
                                        ['name' => 'Veldrif'],
                                        ['name' => 'Vredenburg'],
                                        ['name' => 'Vredendal'],
                                        ['name' => 'West Beach'],
                                        ['name' => 'Yzerfontein'],
                                ],
                            ],
                        ],
                    ],
                
        ];

        foreach ($locations as $location) {
            \App\Models\Location::create($location);
        }
    }
}
